export const ApiPaths = {
  BASE_URL: 'https://tasks.app.rs.school/angular',
  SIGN_UP: '/registration',
  SIGN_IN: '/login',
  PROFILE: '/profile',
  LOGOUT: '/logout',
  GROUPS_LIST: '/groups/list',
  GROUPS_CREATE: '/groups/create',
  GROUPS_DELETE: '/groups/delete',
  GROUPS_DIALOG: '/groups/read',
  GROUPS_SEND_MESSAGE: '/groups/append',
  PEOPLE_LIST: '/users',
  CONVERSATIONS_LIST: '/conversations/list',
  CONVERSATION_CREATE: '/conversations/create',
  CONVERSATION_SEND_MESSAGE: '/conversations/append',
  CONVERSATION_MESSAGES: '/conversations/read',
  CONVERSATION_DELETE: '/conversations/delete',
};
